##############
# Taps
tap "homebrew/bundle"

##############
# Binaries & Tools
brew 'asdf'
brew 'autoconf'
brew 'bat'
brew 'btop'
brew 'cmake'
brew 'curl'
brew 'coreutils'
brew 'cmatrix'
brew 'direnv'
brew 'fd'
brew 'fzf'
brew 'figlet' # ascii art
brew 'git'
brew 'gh'
brew 'gcc'
brew 'gmp'
brew 'htop'
brew 'lazygit'
brew 'lazydocker'
brew 'libyaml'
brew 'lsd'
brew 'jq'
brew 'make'
brew 'mas'
brew 'neovim'
brew 'neofetch'
brew 'pv'
brew 'ripgrep' # required for telescope
brew 'readline'
brew 'sqlite'
brew 'stow'
brew 'starship'
brew 'sl'
brew 'superfile'
brew 'tfenv'
brew 'tmux'
brew 'tree'
brew 'openssl'
brew 'unzip'
brew 'wget'
brew 'zsh-autosuggestions'
brew 'zero-sh/tap/apply-user-defaults'

###############
# Applications
# Misc.
cask 'zen-browser'
cask 'slack'
cask 'spotify'
cask 'notion'
cask '1password'
cask 'qmk-toolbox'
cask 'MonitorControl'
cask 'rectangle'
cask 'alt-tab'
cask 'raycast'
cask 'cleanshot'
cask 'screen-studio'
cask 'keycastr'
cask 'notchnook'
# cask 'jordanbaird-ice' # Macos toolbar

# Development Tools
cask 'ghostty'
cask 'warp'
cask 'visual-studio-code'
# NOTE: cask not supported on apple silicon `cask 'zed'`
cask 'tower'
cask 'gitbutler'
cask 'orbstack'

# Fonts
cask 'font-fira-code-nerd-font'

## AI Tools
cask 'claude-code'
brew 'opencode'

###############
# Mac App Store
mas "system-color-picker", id: 1545870783

###############
# Hooks
